# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/buildpack-deps:disco
    steps:
      - checkout
      - run:
          name: Creating workspace directory
          command: mkdir -p ~/workspace
      - run:
          name: Build application packages
          command: make all
      - run:
          name: Copy artefacts to workspace
          command: cp -r ./artefacts ~/workspace
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - artefacts/*
  plan:
    working_directory: ~/repo
    docker:
      - image: hashicorp/terraform:0.12.6
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Create Terraform RC with Token
          command: |
            echo "credentials \"app.terraform.io\" { token = \"$TF_TOKEN\" }" > ~/.terraformrc
      - run:
          name: Init Terraform providers
          command: terraform init
      - run:
          name: Create Plan
          command: terraform plan -out ~/workspace/atlas.tfplan
      - store_artifacts:
          path: ~/workspace/atlas.tfplan
          destination: atlas.tfplan
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - atlas.tfplan
  execute:
    working_directory: ~/repo
    docker:
      - image: hashicorp/terraform:0.12.6
    steps:
      - checkout
      - run:
          name: Create Terraform RC with Token
          command: |
            echo "credentials \"app.terraform.io\" { token = \"$TF_TOKEN\" }" > ~/.terraformrc
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Copy workspace artefacts to working directory
          command: cp -r ~/workspace/artefacts ./artefacts
      - run:
          name: Init Terraform providers
          command: terraform init
      - run:
          name: Execute Plan
          command: terraform apply ~/workspace/atlas.tfplan
workflows:
  version: 2
  master_commit:
    jobs:
      - build
      - plan:
          requires:
            - build
      - hold:
          requires:
            - plan
          type: approval
      - execute:
          requires:
            - hold
